### ISSUE TITLE
[Camera] Camera moves to the left when you reach the ending

### ISSUE THREAD

**Issue by JaumeMontagut** [thedoctormarc/DOOM_2D19#32]
**Bug description**
If you reach the end door and look to the left, the camera moves to the previous position, making you unable to see the player.

**Steps to reproduce**
1. Reach the end door without killing any enemy.
2. Move the left joystick left and right repeatedly.

**Expected behaviour**
The character moves, but the camera stays in the same place.

**Actual behaviour**
The camera moves to its previous position.

**Game version**
0.4

**Screenshots**
![image](https://user-images.githubusercontent.com/36292291/61997834-f3556e00-b0a7-11e9-8a90-6e19f9c5be60.png)
![image](https://user-images.githubusercontent.com/36292291/61997854-1da72b80-b0a8-11e9-914f-82a95c399ce0.png)

**Comment by thedoctormarc** [comment]
It is an aprehensive camera: it has seen too much blood, and it does not want you to go to the next level and keep killing... :)
Therefore it sets you back... Whatever

**Comment by thedoctormarc** [comment]
If this was hard to correct ir would be major, but I set it to moderate because it is easily percieved, distinguished both visually and in the code, and at the same time it is an accessible and simple chunk of code with little interference with other areas and of a reallyshort and targeted solution which is more like a tweak

**Comment by thedoctormarc** [comment]
I claim it fixed, although patched is a more accurate term. There is a prevention when the scroll right is called, so if speed is positive (to the left) it does not call camera scroll
