### ISSUE TITLE
[Collision] Character going back and forward against a platform

### ISSUE THREAD

**Issue by JaumeMontagut** [thedoctormarc/DOOM_2D19#33]
**Bug description**
If you move against a platform, the character goes back for ~1 frame and instanty comes back.

**Comment by thedoctormarc** [comment]
I believe this refers to the fact that between one frame and another, the player collider gors a bit trough the platform.
Then, the code sets the player back so its visually "glued" to the floor.
If this method is not used, then there should be a way to anticipate collisions, but it may be overkill
