### ISSUE TITLE
[Pathfinding] Enemies near borders can't reach you

### ISSUE THREAD

**Issue by JaumeMontagut** [thedoctormarc/DOOM_2D19#35]
**Bug description**
In the second section, the enemies can jump to the upper platform if they are in a distance to the border. If they are very close, they seem to collider with it and are not able to jump to where you are.

**Steps to reproduce**
1. Make the enemies move close to the border of the platform.
2. Position yourself on the border of the platform.

**Expected behaviour**
They jump, in the same way they would do it if they were on a certain distance to the platform.

**Actual behaviour**
They stay there, trying to jump every certain time, but they never reach you or attack you.

**Game version**
0.4

**Screenshots**
![image](https://user-images.githubusercontent.com/36292291/61998008-cb670a00-b0a9-11e9-88bd-950909faa8a3.png)

**Comment by thedoctormarc** [comment]
This was just because they cannot be spawned there, they are already inside the offset from the platform. They should be spawned at a distance

**Comment by thedoctormarc** [comment]
This duplicate, i will keep #38
