### ISSUE TITLE
[Enemy] IMP does not move to you if you're in the same y position

### ISSUE THREAD

**Issue by JaumeMontagut** [thedoctormarc/DOOM_2D19#36]
**Bug description**
If you are in a platform just above or below the enemy, the enemy will not jump or fall to get to you.

**Expected behaviour**
In screenshot 1, the enemy falls to the left and starts attacking you.
In screenshot 2, the enemy jumps to the left platform, then to yours and starts attacking you.

**Game version**
0.4

**Screenshots**
![image](https://user-images.githubusercontent.com/36292291/61998062-927b6500-b0aa-11e9-8a1b-9ac9c22bc21b.png)
*Screenshot 1*

![image](https://user-images.githubusercontent.com/36292291/61998069-a45d0800-b0aa-11e9-9bb1-103924807c97.png)
*Screenshot 2*

**Additional context**
May be caused because the enemy follows you in x, and when you are in the same y position, it doesn't create a path to you.

**Comment by thedoctormarc** [comment]
This may happen because the player target tile pos is set one tile above where it should be, so enemy goes there
