### ISSUE TITLE
[Enemy] Cacodemon doesn't aim correctly

### ISSUE THREAD

**Issue by JaumeMontagut** [thedoctormarc/DOOM_2D19#37]
**Bug description**
Cacodemon doesn't aim correctly

**Steps to reproduce**
1. Stand still in the same section where the cacodemon is.
2. Let the cacodemon shoot you.

**Expected behaviour**
The projectile hits you.

**Actual behaviour**
The projectile impacts on the ground and doesn't do any damage to you.

**Game version**
0.4

**Screenshots**
![image](https://user-images.githubusercontent.com/36292291/61998094-20efe680-b0ab-11e9-9f13-b6f22044250e.png)

**Additional context**
Maybe all the logic is correct, but the point from which the bullet is lower from the one which is used to calculate the vector.

**Comment by thedoctormarc** [comment]
Right now it is calculated with the raw player and enemy pos.
Instead, it should calculate it with the shot spawn pos + half the shot width and the player central point

**Comment by thedoctormarc** [comment]
Solved. Its pretty cute now with raycasts
