### ISSUE TITLE
[Pathfinding] A to B enemy type does not follow when player on the leftmost same-platform tile

### ISSUE THREAD

**Issue by JaumeMontagut** [thedoctormarc/DOOM_2D19#38]
**Steps to reproduce**
1. Stand close to the platform (with one foot on the air).

**Expected behaviour**
The enemy comes to you and starts attacking.

**Actual behaviour**
The enemy stands there doing nothing, I can even shoot at it and it doesn't react.

**Game version**
0.4

**Screenshots**
![image](https://user-images.githubusercontent.com/36292291/61998141-9fe51f00-b0ab-11e9-95db-ade8a046ec82.png)

**Additional context**
Probably non navigable zone reaches the area where I'm standing because the player position isn't on his right feet, but on the center of its body.

**Comment by thedoctormarc** [comment]
Extra data: this happens with a to b enemies (Hellknight and Baron of Hell)

**Comment by thedoctormarc** [comment]
This is duplicate :/, i will keep the other
