### ISSUE TITLE
[Moving platform] Moving platform catches you

### ISSUE THREAD

**Issue by JaumeMontagut** [thedoctormarc/DOOM_2D19#39]
**Steps to reproduce**
1. Place yourself under the vertical moving platform.
2. Let it go down.

**Expected behaviour**
When the platform goes up, it catches you and brings you with it.

**Actual behaviour**
You die because you get crushed by the platform. You could also get pushed away.

**Video**
[![Bug video](https://img.youtube.com/vi/LmC0xd31EYU/0.jpg)](https://www.youtube.com/watch?v=LmC0xd31EYU)
[Video link](https://www.youtube.com/watch?v=LmC0xd31EYU)

**Game version**
0.4

**Additional context**
This was a funny bug to find  😂

**Comment by thedoctormarc** [comment]
I mean you could smell this happenning from far away far away, and it has xd

**Comment by thedoctormarc** [comment]
Mmm at this very moment, haven't decided an approach between:
1) Just separate vertical dynamic platforms from the other ones in the X axis
2) Put the player to the fall state when the situation in the video occurs
The first one would come in reallt handy to avoid weird collisions

**Comment by thedoctormarc** [comment]
Update: now that i watch the video I believe the most intuitive approach is that the player is just set to the fall state there
