### ISSUE TITLE
[Collision] Moving to the right at the same time you jump prevents you to jump to the full height

### ISSUE THREAD

**Issue by JaumeMontagut** [thedoctormarc/DOOM_2D19#40]
**Steps to reproduce**
1. Stand as seen on the screenshot.
2. Move the joystick to the right.
3. Jump

**Expected behaviour**
You don't reach the platform.

**Actual behaviour**
You jump the same distance and reach the platform.

**Game version**
0.4

**Screenshots**
![image](https://user-images.githubusercontent.com/36292291/61998298-2f8bcd00-b0ae-11e9-8ab6-f23a59068e93.png)

**Comment by thedoctormarc** [comment]
This is actually intended. It is usefuk when you are next to a wall and must have an extra impulse, because you do not have X offset to reach the top, since you are close to the wall, so the only time where you can move in the X axis is when you get to the top in the Y pos
