### ISSUE TITLE
[Sound] If you get killed while using the chainsaw, its sound repeats infinitely

### ISSUE THREAD

**Issue by JaumeMontagut** [thedoctormarc/DOOM_2D19#41]
**Bug description**
If you get killed while using the chainsaw, its sound repeats infinitely.

**Steps to reproduce**
1. Hold the right trigger to use the chainsaw.
2. Get killed by an enemy (like the Cacodemon).

**Comment by thedoctormarc** [comment]
I had that in mind. Nice catch!
