### ISSUE TITLE
[Enemy] Enemy shoots you even if it can't hit you

### ISSUE THREAD

**Issue by JaumeMontagut** [thedoctormarc/DOOM_2D19#43]
**Steps to reproduce**
1. Stand as seen on the screenshot.

**Expected behaviour**
The enemy continues to patrol (there is a wall between you and them so they shouldn't be able to see you).

**Actual behaviour**
The enemy shoots at you.

**Game version**
0.4

**Screenshots**
![image](https://user-images.githubusercontent.com/36292291/61998407-d3c24380-b0af-11e9-8b9f-506b43bde6a4.png)

**Comment by thedoctormarc** [comment]
In the future, will work on a raycast or smth to detect a wall in between and abort shot triggering
